apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: ejemplito
type: Opaque
data:
  user: YWRtaW5heg==       # base64 de 'adminaz'
  pass: UmFmYWVsMjc=       # base64 de 'Rafael27'