apiVersion: v1
kind: Service
metadata:
  name: nlb-service
  namespace: ejemplito
spec:
  type: LoadBalancer
  selector:
    app: micros
  ports:
    - name: client
      port: 8000
      targetPort: 8000
      protocol: TCP
    - name: service
      port: 8080
      targetPort: 8080
      protocol: TCP